### ISSUE TITLE
Error! Check the URL!

### ISSUE THREAD

**Issue by Tommy270502** [revoxhere/Pretty-YouTube-Downloader#1]
So I have tried your Pretty Youtube Downloader and it just constantily returns me this error no matter what type of file type I am trying to download. Also, I have tried different links and all of them returned the same error. The Python script then also returns this message. Any known solution to this problem?

`ERROR: Postprocessing: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location`

**Comment by revoxhere** [comment]
As the error says, you don't have ffmpeg installed (sudo apt install ffmpeg)
